Fix location of `preload.js` for playwright tests
electron-react-boilerplate/electron-react-boilerplate pull request #3369
Opened 2022-12-01 21:18 UTC by jfilter

Without this change, the Playwright guide is not working: https://electron-react-boilerplate.js.org/docs/integration-tests

Thanks for your work!

2023-01-04 02:32 UTC, amilajack requested changes

2023-01-04 02:32 UTC, amilajack commented on src/main/main.ts
> -      preload: app.isPackaged
this will break in cases where the app is running with a prod build but hasn't been packaged

2023-01-04 02:33 UTC, amilajack commented on src/main/main.ts
> -      preload: app.isPackaged
we could try testing against `process.env.NODE_ENV === 'test'`

2023-02-05 20:10 UTC, closed without merging

2023-03-18 22:16 UTC, silvio2402 commented
Hey, I think this should be worked on to find a suitable solution.
Can someone create an issue?
As mentioned by @jfilter, Playwright isn't working after using the guide because of this issue.
Thanks and have a nice day!